{
	"version": 1652379922,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/bullet-sheet0.png",
		"images/asteroid-sheet0.png",
		"images/lifebar.png",
		"images/lifeborder-sheet0.png",
		"images/thrust-sheet0.png",
		"images/thrust-sheet1.png",
		"images/thrust-sheet2.png",
		"images/brakes-sheet0.png",
		"images/brakes-sheet1.png",
		"images/brakes-sheet2.png",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/jetloop1.m4a",
		"media/jetloop1.ogg",
		"media/lazer fire 1.m4a",
		"media/lazer fire 1.ogg",
		"media/newachievement1.m4a",
		"media/newachievement1.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"media/ui1.m4a",
		"media/ui1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}